namespace TotoroNext.Module;

public static class CommonIcons
{
    public const string Add = nameof(Add);
    public const string Alarm = nameof(Alarm);
    public const string ArrowDown = nameof(ArrowDown);
    public const string ArrowUp = nameof(ArrowUp);
    public const string ArrowUpDown = nameof(ArrowUpDown);
    public const string Bookmark = nameof(Bookmark);
    public const string CalendarClock = nameof(CalendarClock);
    public const string Check = nameof(Check);
    public const string ChevronLeft = nameof(ChevronLeft);
    public const string ChevronRight = nameof(ChevronRight);
    public const string ClearAll = nameof(ClearAll);
    public const string CopyToClipboard = nameof(CopyToClipboard);
    public const string DebugPause = nameof(DebugPause);
    public const string Delete = nameof(Delete);
    public const string Download = nameof(Download);
    public const string Downloads = nameof(Downloads);
    public const string Edit = nameof(Edit);
    public const string Ending = nameof(Ending);
    public const string FilePath = nameof(FilePath);
    public const string Filter = nameof(Filter);
    public const string Fullscreen = nameof(Fullscreen);
    public const string FullscreenExit = nameof(FullscreenExit);
    public const string Home = nameof(Home);
    public const string HourglassFill = nameof(HourglassFill);
    public const string Incognito = nameof(Incognito);
    public const string List = nameof(List);
    public const string MemoryTrash = nameof(MemoryTrash);
    public const string MonitorPlayFill = nameof(MonitorPlayFill);
    public const string MusicNote = nameof(MusicNote);
    public const string NewReleases  = nameof(NewReleases);
    public const string Opening = nameof(Opening);
    public const string Pause = nameof(Pause);
    public const string Play = nameof(Play);
    public const string Rss = nameof(Rss);
    public const string Search = nameof(Search);
    public const string Settings = nameof(Settings);
    public const string Extensions = nameof(Extensions);
    public const string SkipNext = nameof(SkipNext);
    public const string SkipPrevious = nameof(SkipPrevious);
    public const string SkipSegments = nameof(SkipSegments);
    public const string Star =  nameof(Star);
    public const string Store = nameof(Store);
    public const string Test = nameof(Test);
    public const string Theme = nameof(Theme);
    public const string Torrent = nameof(Torrent);
    public const string TorrentClient = nameof(TorrentClient);
    public const string Tracking = nameof(Tracking);
    public const string Update = nameof(Update);
    public const string VideoLibrary = nameof(VideoLibrary);
    public const string VideoPlayer = nameof(VideoPlayer);
}